### PR TITLE
Fix build with Python 3.12.

### PR DESCRIPTION
**Pull request by 0-wiz-0**
https://docs.python.org/3.12/whatsnew/3.12.html#configparser

### CODE REVIEW

**Comment by adiroiban** [comment]
Thanks.

It looks like we need to update the CI to GitHub Actions as this is still configured to Travis

Once that is done, I think we can update the PyPI publishing process, 

and we should be ready for a new release.

**Comment by adiroiban** [comment]
PR for CI ready for review - https://github.com/twisted/constantly/pull/33

I hope we can merge that PR and then rebase this PR and check that it works on 3.12

**Comment by adiroiban** [comment]
This PR needs to update the ci.yaml and enable the tests on 3.12 to see that they fail before the patch and they pass after the patch

**Comment by graingert** [comment]
Thanks for the PR, this was resolved in https://github.com/twisted/constantly/pull/35

**Pull request closed without merging**
