### PR TITLE
Split Constantly out into its own project.

### PR DESCRIPTION
**Pull request by hawkowl**
This does the following:

- Updates code references
- Adds Tox, for py26, py27, pypy, coverage and pyflakes
- Adds a basic README and LICENSE
- Adds a setup.py
- Adds versioneer

### CODE REVIEW

**Comment by hawkowl** [comment]
Finally got back to this. 

I read through the tests and made sure that the links were right. There's some pydoctors errors, but that's because PyDoctor has problems with the weird subclassing situation that Constantly does.

I think it's in somewhat of a shape now.

**Comment by rbtcollins** [comment]
@cyli I test unittest2 on python 3.3 before every release. When you say it doesn't work, can you provide a trace, or file a ticket at https://github.com/testing-cabal/unittest-ext ?

**Comment by cyli** [comment]
@rbtcollins  My memory for these things is basically about two weeks, so I have no idea any more.  :)  I'll try it again later though.

**Comment by hawkowl** [comment]
Since this has kind of sat for long enough, I'm going to merge it unless anyone has any objections.

**Comment by jml** [comment]
LGTM.

**Pull request merged**
